name: Terraform Spacelift Stack
description: Create a Terraform Spacelift Stack
title: "[Stack]: "
labels: ["stack", "spacelift", "terraform"]
body:
  - type: markdown
    attributes:
      value: Use this form to request creation of a Spacelift Stack for a Terraform based deployment.
  - type: dropdown
    id: team
    attributes:
      label: Team
      description: Please select your team from the dropdown.
      multiple: false
      options:
        - "cloud-platform"
        - "security-engineering"
    validations:
      required: false
  - type: dropdown
    id: organization
    attributes:
      label: Organization
      description: The name of the organization your repository is a part of.
      multiple: false
      options:
        - "AtheneUSA-EMU"
        - "ath-cloud-platform"
    validations:
      required: true
  - type: input
    id: repository_name
    attributes:
      label: Repository Name
      description: The name of the repository the stack will deploy from. This value must match the name in GitHub exactly.
      placeholder: "AWS_Account_Automation"
    validations:
      required: true
  - type: input
    id: project_root
    attributes:
      label: Project Root
      description: Provide the path within the repository to the folder containing your infrastructure as code files. Defaults to the root of the repository.
      placeholder: "/infra"
    validations:
      required: false
  - type: input
    id: branch
    attributes:
      label: Deployment Branch
      description: The name of the branch that is used for this stack's deployments.
      placeholder: "main"
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Please select the environment of the AWS account you are deploying to.
      multiple: false
      options:
        - "dev"
        - "qa"
        - "stage"
        - "prod"
    validations:
      required: true
  - type: input
    id: account_number
    attributes:
      label: Account Number
      description: The AWS account number this Spacelift stack will deploy to.
      placeholder: "123456789012"
    validations:
      required: true
  - type: input
    id: terraform_version
    attributes:
      label: Terraform Version
      description: Provide a default version of Terraform that your project requires. Value cannot go higher than 1.5.7.
      placeholder: "1.5.7"
    validations:
      required: true
